# Generated by Django 4.1.2 on 2022-10-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytodos',
            options={'ordering': ['complete']},
        ),
        migrations.AddField(
            model_name='mytodos',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mytodos',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mytodos',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mytodos',
            name='task',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
